#!/usr/bin/env python3
# vim: et ts=8 sw=4 sts=4 ai

import readline
import cmd
import pdb
import os.path
from ctypes import *

class uart_packet(Structure):
    ERTM14_MAX_UART_LINK_PAYLOAD = 512
    _fields_ =[
        ("ptype", c_ubyte),
        ("length", c_ushort), 
        ("payload", c_ubyte*ERTM14_MAX_UART_LINK_PAYLOAD),
    ]

class uart_link(Structure):
    _fields_ =[
        ("send_byte", c_void_p),
        ("recv_byte", c_void_p),
        ("get_ms_tics", c_void_p),
        ("priv", c_void_p),
        ("state", c_int),
        ("rx_count",  c_int),
        ("rx_crc, check_crc", c_ushort),
        ("rx_last_tics", c_uint),
        ("rx_packet", uart_packet),
    ]

class ertm_connection(Structure):
    PATH_MAX = 4096
    _fields_ = [
        ("address", c_char_p),
        ("serial_connection", c_char*PATH_MAX),
    ]


class ertm_status(Structure):
    _fields_ = [
        ("connection", ertm_connection),
        ("state", c_void_p),
        ("link", uart_link),
        ("reserved", 64*c_uint),
    ]

class ertm_wr_status(Structure):
    _fields_ = [
	("VER", c_uint),
	("CTRL", c_uint),
	("WDIAG_SSTAT", c_uint),
	("WDIAG_PSTAT", c_uint),
	("WDIAG_PTPSTAT", c_uint),
	("WDIAG_ASTAT", c_uint),
	("WDIAG_TXFCNT", c_uint),
	("WDIAG_RXFCNT", c_uint),
	("WDIAG_SEC_MSB", c_uint),
	("WDIAG_SEC_LSB", c_uint),
	("WDIAG_NS", c_uint),
	("WDIAG_MU_MSB", c_uint),
	("WDIAG_MU_LSB", c_uint),
	("WDIAG_DMS_MSB", c_uint),
	("WDIAG_DMS_LSB", c_uint),
	("WDIAG_ASYM", c_uint),
	("WDIAG_CKO", c_uint),
	("WDIAG_SETP", c_uint),
	("WDIAG_UCNT", c_uint),
	("WDIAG_TEMP", c_uint),
    ]

class ErtmTest(cmd.Cmd):

    prompt = 'ertm> '
    ruler = '-'
    history = os.path.join(os.path.expanduser('~'), '.ertm_history')

    ERTM_CLKA = 0
    ERTM_CLKB  = 1
    ERTM_LO = 2
    ERTM_REF = 3

    Sensor_Array = 20 * c_double
    BoardInfo = 80 * c_uint

    connector_idx = {
        'lo' : ERTM_LO,
        'ref' : ERTM_REF,
        'clka': ERTM_CLKA,
        'clkb': ERTM_CLKB,
    }

    def errmsg(self, errcode):
        ertm_perror = self.lib.ertm_perror
        ertm_perror.restype = c_char_p
        msg = self.lib.ertm_perror(errcode)
        return str(msg, encoding='utf8')

    def my_preloop(self):
        try:
            readline.read_history_file(self.history)
        except FileNotFoundError:
            readline.write_history_file(self.history)
        self.lib = CDLL('./libertm.so')
        self.display = CDLL('./display.so')
        ertm_init = self.lib.ertm_init
        ertm_init.restype = POINTER(ertm_status)
        self.handle = ertm_init('/dev/ttyUSB2')
        if not self.handle:
            print('could not open USB device')
            exit()

    def do_get_board_state(self, args):
        "get complete CLKAB and REF/LO status."
        buf = create_string_buffer(512)
        self.lib.ertm_get_board_config(self.handle, byref(buf))
        self.display.display_ertm_state(byref(buf))

    def do_set_freq(self, args):
        "set frequency of connector or connector channel."
        try:
            connector, rest = args.split(maxsplit=1)
            connector = self.connector_idx[connector.lower()]
            if connector in (self.ERTM_CLKA, self.ERTM_CLKB):
                print(rest)
                channel, freq = rest.split()
                channel = int(channel)
                freq = int(freq, 0)     # FIXME: this needs units
            else:
                channel = 10            # don't care
                freq = rest
                freq = int(freq, 0)     # FIXME: this needs units
        except (ValueError, KeyError) as e:
            print('usage: set_freq/sf {clka|clkb|lo|ref} [channel] freq')
            return
        err = self.lib.ertm_set_freq(self.handle, connector, channel, freq)
        if err:
            msg = self.errmsg(err)
            print('error {} in set_freq: {}'.format(err, msg))
            return

    def do_enable_channel(self, args):
        "enable/disable individual connector channel."
        try:
            connector, channel, *enable = args.split()
            connector = self.connector_idx[connector.lower()]
            channel = int(channel)
            enable = int(enable[0]) if enable else 1
        except (ValueError, KeyError) as e:
            print('usage: enable_channel/ec {clka|clkb|lo|ref} channel [0|1]')
            return
        err = self.lib.ertm_channel_enable(self.handle, connector, channel, enable)
        if err:
            msg = self.errmsg(err)
            print('error {} in enable_channel: {}'.format(err, msg))
            return

    def do_disable_channel(self, args):
        "disable individual connector channel."
        try:
            connector, channel = args.split()
            connector = self.connector_idx[connector.lower()]
            channel = int(channel)
        except (ValueError, KeyError) as e:
            print('usage: disable_channel/dc {clka|clkb|lo|ref} channel')
            return
        err = self.lib.ertm_channel_enable(self.handle, connector, channel, 0)
        if err:
            msg = self.errmsg(err)
            print('error {} in disable_channel: {}'.format(err, msg))
            return

    def do_get_level_adjust(self, args):
        "display amplification level of connector."
        try:
            connector = args
            connector = self.connector_idx[connector.lower()]
        except (ValueError, KeyError) as e:
            print('usage: get_level_adjust/gla {lo|ref}')
            return
        level = c_double()
        err = self.lib.ertm_dds_get_level_adjust(self.handle, connector, byref(level))
        if err:
            msg = self.errmsg(err)
            print('error {} in get_level_adjust: {}'.format(err, msg))
            return
        print('{} level = {}'.format(args.upper(), level.value))

    def do_set_level_adjust(self, args):
        "set amplification level of connector."
        try:
            connector, level = args.split()
            connector = self.connector_idx[connector.lower()]
            level = float(level)
        except (ValueError, KeyError) as e:
            print('usage: set_level_adjust/sla {lo|ref} LEVEL')
            return
        self.lib.ertm_dds_set_level_adjust(self.handle, connector, c_double(level))

    def do_wrc_diags(self, args):
        "get WRC diagnostics."
        buf = ertm_wr_status()
        self.lib.ertm_wr_diags(self.handle, byref(buf))
        self.display.display_wrc_diags_cooked(byref(buf))

    def do_wr_status(self, args):
        "get WRC link/lock status."
        link_up = c_int()
        is_locked = c_int()
        self.lib.ertm_wr_status(self.handle, byref(link_up), byref(is_locked))
        msg ="link: {} PLL: {}".format(
                    "up" if link_up else "down",
                    "locked" if is_locked else "not locked")
        print(msg)

    def do_wr_enable(self, args):
        "start/stop WR PTP daemon."
        try:
            enable = int(args) if args else 1
        except (ValueError, KeyError) as e:
            print('usage: wr_enable [0|1] (default=1/enable)')
            return
        self.lib.ertm_wr_enable(self.handle, enable)

    def do_wr_disable(self, args):
        """stop PTP daemon (synonymous to "wr_enable 0")."""
        self.lib.ertm_wr_enable(self.handle, 0)

    def do_temperatures(self, args):
        """display temperature sensor readings."""
        temps = self.Sensor_Array()
        self.lib.ertm_get_temperatures(self.handle, byref(temps))
        self.display.display_temperatures(byref(temps))

    def do_voltages(self, args):
        """display voltage sensor readings."""
        volts = self.Sensor_Array()
        self.lib.ertm_get_voltages(self.handle, byref(volts))
        self.display.display_voltages(byref(volts))

    def do_board_info(self, args):
        """display board version info."""
        bi = self.BoardInfo()
        self.lib.ertm_get_board_info(self.handle, byref(bi))
        self.display.display_version_info(byref(bi))

    def my_postloop(self):
        readline.write_history_file(self.history)
        self.lib.ertm_exit(self.handle)

    def do_headers(self, args):
        "display the help headers."
        print(self.doc_header)
        print(self.misc_header)
        print(self.undoc_header)

    def do_EOF(self, arg):
        print()
        return True

    def do_h(self, arg):
        self.do_help(arg)

    # catch Ctrl-C and drop me back into cli
    def cmdloop_intr(self, intro=None):
        self.my_preloop()
        while True:
            try:
                self.cmdloop()
                break
            except KeyboardInterrupt as e:
                print('^C')
        self.my_postloop()

    # convenience aliases
    do_q = do_EOF
    do_quit = do_EOF
    do_gbs = do_get_board_state
    do_sla = do_set_level_adjust
    do_gla = do_get_level_adjust
    do_wrd = do_wrc_diags
    do_temp = do_temperatures
    do_volt = do_voltages
    do_bi = do_board_info

if __name__ == '__main__':

    tst = ErtmTest(completekey='tab')
    tst.cmdloop_intr('programa de test')
